# version format
version: 1.13.1.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=

# Test against this version of Node.js
environment:
  ruby_version: 22-x64
  nodejs_version: "0.10"

cache:
- C:\Ruby%ruby_version%\lib\ruby\gems
- C:\mingw64

# Install scripts. (runs after repo cloning)
install:
  - git clone https://github.com/sass/sassc.git
  - git clone https://github.com/sass/sass-spec.git
  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ps: |
      if(!(gem which minitest 2>$nul)) { gem install minitest --no-ri --no-rdoc }
      if ($env:Compiler -eq "mingw" -AND -Not (Test-Path "C:\mingw64")) {
        # Install MinGW.
        $file = "x86_64-4.9.2-release-win32-seh-rt_v4-rev3.7z"
        $url  = "https://bintray.com/artifact/download/drewwells/generic/"
        $url += $file
        Invoke-WebRequest -UserAgent wget -Uri $url -OutFile $file
        &7z x -oC:\ $file > $null
      }
  - set PATH=C:\mingw64\bin;%PATH%
  - set CC=gcc
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - cmd: ECHO Changing directory to Merchello.Web.UI.Client
  - ps: cd  src\Merchello.Web.UI.Client
  - npm install
  - npm install -g grunt-cli
  - npm install grunt-sass
  - ps: grunt build
  - cmd: ECHO Changing directory back to Merchello

build_script:
- build-appveyor.cmd

test:
   assemblies:
      - 'Merchello.Tests.IntegrationTests.dll'

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip

deploy:
     # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/merchello/api/v2/
    symbol_server: https://www.myget.org/F/merchello/symbols/
    api_key:
      secure: 34B4mXhAYW6XOw8H9ZVh+KhbKKjXnb8QIp8bpoIKrkx5Uivcg0D4cRbu/pvdI65o
    artifact: /.*\.nupkg/
    on:
      branch: appveyor

 #9af0279b-c6c1-4dfd-b3cb-901515f7a753
 #https://www.myget.org/F/merchello/symbols/