# version format
version: 1.13.2.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=

# Test against this version of Node.js
environment:
  ruby_version: 22-x64
  nodejs_version: "0.10"

cache:
- C:\Ruby%ruby_version%\lib\ruby\gems

# Install scripts. (runs after repo cloning)
install:
  #- git clone https://github.com/sass/sassc.git
  #- git clone https://github.com/sass/sass-spec.git
  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install sass
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - cmd: ECHO Changing directory to Merchello.Web.UI.Client
  - ps: cd  src\Merchello.Web.UI.Client
  - npm install
  - npm install -g grunt-cli
  - ps: grunt build
  - cmd: ECHO Changing directory back to Merchello
  - ps: cd  ..\..

build_script:
- build-appveyor.cmd

test:
   assemblies:
      - 'test\Merchello.Tests.IntegrationTests\Release\Merchello.Tests.IntegrationTests.dll'

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip

deploy:
     # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/merchello/api/v2/
    symbol_server: https://www.myget.org/F/merchello/symbols/
    api_key:
      secure: 34B4mXhAYW6XOw8H9ZVh+KhbKKjXnb8QIp8bpoIKrkx5Uivcg0D4cRbu/pvdI65o
    artifact: /.*\.nupkg/
    on:
      branch: appveyor

 #9af0279b-c6c1-4dfd-b3cb-901515f7a753
 #https://www.myget.org/F/merchello/symbols/